### ISSUE TITLE
[BUG]? 鼠标经过必卡，Mac，Chrome，是浏览器某些设置原因还是脚本自身问题？

### ISSUE THREAD

**Issue by BlackSpacee** [adamlui/github-star-history#27]
RT

**Comment by adamlui** [comment]
@BlackSpacee 嘿，我正在使用谷歌翻译，鼠标悬停卡住是什么意思？

**Comment by BlackSpacee** [comment]
> @BlackSpacee 嘿，我正在使用谷歌翻译，鼠标悬停卡住是什么意思？

When hovering over the generated GitHub star history image, I cannot click on anything on the entire webpage.  and subsequently, the entire browser tab crashes. I'm not sure if it's due to certain settings on my computer's browser or an issue with the script itself.

**Comment by adamlui** [comment]
@BlackSpacee can you tell me what is the browser and userscript manager you use? Also does it happen with every other userscript and browser extension disabled?

**Comment by BlackSpacee** [comment]
@adamlui Mac Chrome latest version, Tampermonkey, I am sure I have turned off other scripts or extensions.

**Comment by BlackSpacee** [comment]
@adamlui  I don't know if it's because of the version update, but it's fixed. It's normal on my side.
