### ISSUE TITLE
BUG 

### ISSUE THREAD

**Issue by ChinaGodMan** [adamlui/github-star-history#38]
在仓库页面内点击左侧边栏跳转新的仓库，跳转之后没有显示starhistory图片

**Comment by adamlui** [comment]
@ChinaGodMan 嘿，我看不懂中文，所以我用谷歌翻译，你能举个例子说明一下哪个页面，点击哪个页面会跳转到哪个页面吗

**Comment by ChinaGodMan** [comment]
![Snipaste_2024-09-02_02-59-46](https://github.com/user-attachments/assets/581eb7ee-2d83-408e-96f7-80f08597e93f)

https://github.com/user-attachments/assets/8cb2dd50-6323-4709-b419-48825437a75b

@adamlui 



> @ChinaGodMan 嘿，我看不懂中文，所以我用谷歌翻译，你能举个例子说明一下哪个页面，点击哪个页面会跳转到哪个页面吗

**Comment by adamlui** [comment]
谢谢 @ChinaGodMan 我修复了这个问题，你可以通过“关于”菜单更新到 2024.9.2 并确认它能正常工作吗

**Comment by ChinaGodMan** [comment]
> 谢谢 @ChinaGodMan 我修复了这个问题，你可以通过 “关于” 菜单更新到 2024.9.2 并确认它能正常工作吗

@adamlui  。正常了。谢谢你。
