### ISSUE TITLE
BUG:Star History图片错误显示

### ISSUE THREAD

**Issue by ChinaGodMan** [adamlui/github-star-history#45]
@adamlui  ❤️ 
亲爱的美国老铁 ❤️ 
有一个问题是在仓库内通过导航栏跳到个人主页时，star history的图片也会显示。

由于GitHub页面发生变化时会重新加载页面元素，这个问题有时会出现，有时不会出现。

猜测原因：似乎是当repo页面`URL`变化时，脚本会运行插入图片，没有针对性的过滤排除一些非repo页面url导致的？
![Screenshot_20241016_160646_edit_358146388323731](https://github.com/user-attachments/assets/db77f84b-ebbb-43f1-9f5d-3fcf2b18e763)
![Screenshot_20241016_160530_edit_358175305354809](https://github.com/user-attachments/assets/c89fbe40-0a2a-4f51-8a96-99c2605f3c0a)

**Comment by adamlui** [comment]
@ChinaGodMan I didn't optimize for mobile before but after some tasks I will try to fix

**Comment by adamlui** [comment]
@ChinaGodMan thank you for your helpful and important report. I have patched it to never occur again. Can you continue using as normal, then maybe a week later close the issue if it doesn't re-occur?
